class:mario
costumes:
- chatcolor: '&3'
  name: §cM§ea§1r§fi§4o
  sig: f903wp57MMvbIAHBXEpbzytkl4BL2NwCFfN/kzwFPug4+4b2+E533DbR3Mi4zRU64DUnuC4AeRYQCn8hg0tL5esd1zCntdDP30ep7KbpsL2iy733e2upzR0ratiQXUkO0xdCspDaizbkY1bQBqjdUgClpohuaGU6wvMKX1nJbaWRMwK2TWp5ER6WQgvYa7mPZcqEYTFQ1+fyscnE3S2VbgeKDwirAOWhPuMgGkScvDYpqvR0GZzIO2b3vFLENaSWgGD2+VpsP/xyJk788d2FfXjEXKWdpDmWcF6nE8iVz5qWdpgtK6k5t+MFpsYbD9aZ5Lr1YCLKPl5spZk29uq0DZcKTcr+FEmaZOWxRBBVvrJd0V70fKX2Dc/8ZnTvVJGDrXo2vIW+jU2gPhBrldnySUZielYV+UecjSB1BphugJywU7kFuGcS91tQMcuiEYwJ8VJ9jT8q5AbD+Clvo7wjggZbDKRpiMF2ueH0PDh0tmBuyEpMQqwb4fibAWmToRtpk9nahOLt7NAo8GvzFJf9lKhzQZvQi8W+8jTqLB/ib/ntBqb6zn3CMFHuBZoBq3PO7hBm0obRQ7Nv1Pdqo8ufVILxC5GukhKbxREziv0O4GL7GQrBHLl3/rx+li2pTOc2B2n9lEDjBKKvd//1xzvlct8fBDdXS5m7xTzcxFOrMPo=
  val:eyJ0aW1lc3RhbXAiOjE1MjEyMzE4MTcxODYsInByb2ZpbGVJZCI6IjQzM2EwZDhlYWE4YTQyYWViYzU0ZjQ0NTZiZjM2NmMwIiwicHJvZmlsZU5hbWUiOiJBbnRpU2VwdGljRXllMSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjY1ZDk1ZTI2MGM4ZWY3ZGJlOTg4ZWQwYTY3ZTVjODQ5NDA4N2E4NmFhZTExOWYzYTM5ODQxOGI5N2IzMCJ9fX0=
effects:
- /effect <plr> 5 9999 10 true
- /effect <plr> 10 9999 1 true
- /effect <plr> 11 9999 2 true
- /effect <plr> 12 9999 1 true
- /effect <plr> 13 9999 1 true
- /effect <plr> 16 9999 1 true
haste: 6
items:
- /give <plr> minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts
jump: 6
maxHearts: 20
permissions:
  superherocity:
  - ch.alias.carryplayer
  - ch.alias.dismountplayer
  - essentials.speed
powers:
- /buff
- /carryplayer <player>
- /dismountplayer
- /jump <0-6>
- /run <0-6>
- /haste <0-6>
- /disguiseviewself
run: 6
speech: Here we goooo!
trail: [
  ]
